### ISSUE TITLE
Solution for "Caused by: java.lang.NumberFormatException: For input string: "2236602580""

### ISSUE THREAD

**Issue by bgrueda** [bgrueda/WES_LUAD#4]
DepthOfCoverage brings important information about the mapped files. It allows to know how are distributed the reads from your samples on the target as part of the preprocessing before the calling of variants. 

I was trying to run the **DepthOfCoverage** tool from gate, with:
`gatk DepthOfCoverage -R hg38.fasta -I mds_ex.bam -L A.bed -O DOC.txt 2>xDOC.log`
 
It asks me for an index for the reference, so I created one with: 
`samtools faidx hg38.fasta`

This time it asked me for a dictionary file for the reference, so I created:
`java -jar ../gatk-4.1.7.0/picard.jar CreateSequenceDictionary R= hg38.fasta O= hg38.fasta.dict 2>xdict.log`
[xdict.log](https://github.com/bgrueda/WES_LUAD/files/5482111/xdict.log)

				
This time is says: "Fasta dict file [...]/hg38.dict for reference [...] does not exist", so changed the name file 
`mv hg38.fasta.dict hg38.dict` 
				
Now I ran: 
`gatk DepthOfCoverage -R hg38.fasta -I mds_ex.bam -L A.bed -O DOC.txt 2>xDOC4.log`
and have this Error: **"Caused by: java.lang.NumberFormatException: For input string: "2236602580""**
     
On all the last tries it not even create the output file. 
So I really don't know what to do next. 

Below you could find the complete log file 
[xDOC4.log](https://github.com/bgrueda/WES_LUAD/files/5479241/xDOC4.log)

And the rest of the files I used are available in:
https://drive.google.com/drive/folders/1AQKJrSDn-PMeHLWZf35DdzZ61hByYSFo?usp=sharing

More infromation about this tool in: 
https://gatk.broadinstitute.org/hc/en-us/articles/360046789152-DepthOfCoverage-BETA-#--reference

the java version that I am using is:
java 14.0.1 2020-04-14

**Comment by IsauraRReinhold** [comment]
In gatk requieres an specific version of java, mybe your version is not the correct

https://gatk.broadinstitute.org/hc/en-us/articles/360035532332-Java-version-issues

**Comment by AliciaMstt** [comment]
The error means this: 
java.lang.NumberFormatException for input string is one of the most common exceptions java programmers face while doing the coding. This exception occurs when someone tries to convert a String into primitive data types such as int, float, double, long, byte, short, etc. It happens only when the String is not valid to be converted into primitive datatype.

https://javahungry.blogspot.com/2020/05/java.lang.numberformatexception-input-string.html

**Comment by IsauraRReinhold** [comment]
Example of java error in stackoverflow

https://es.stackoverflow.com/questions/306845/exception-in-thread-main-java-lang-numberformatexception-for-input-string

**Comment by redgcko7** [comment]
It looks like this error has been documented in the Broad Institute forum, mainly when using the command 'VariantFiltration':

https://gatk.broadinstitute.org/hc/en-us/search?utf8=%E2%9C%93&query=Caused+by%3A+java.lang.NumberFormatException%3A+For+input+string

There doesnt seem to be a simple fix, depends on each person's input I think...

**Comment by bgrueda** [comment]
We are consider two options: 

1. The first one that is that maybe is an error of the inputs.  So trying a new bed file could be the solution since the number "2236602580" is in this file as a coordinate. 

2. The second one is that maybe as the tool is a BETA version, it could have many issues yet. There is reported this kind of problems on other tools from the same toolkit.

**Comment by AliciaMstt** [comment]
Referencia de formato bed: https://genome.ucsc.edu/FAQ/FAQformat.html#format1

**Comment by IsauraRReinhold** [comment]
convert fasta to bed format

https://bioinformatics.stackexchange.com/questions/91/how-to-convert-fasta-to-bed

**Comment by bgrueda** [comment]
The problem was with the BED file, so I ran again with a new bed file with the first three chromosomes and it worked and finally creates the files it suppose to created.
