### ISSUE TITLE
How to cite using Manubot? (for dummies)

### ISSUE THREAD

**Issue by bgrueda** [bgrueda/WES_LUAD#5]
**Manubot** is a  a workflow and set of tools for the next generation of scholarly publishing. Write your manuscript in markdown, track it with git, automatically convert it to .html, .pdf, or .docx, and deploy it to your destination of choice.

It uses *Python* and one of the main facilities is the **automated citation**.

It suppose to be as easy as:
```
pip install --upgrade manubot 

manubot cite doi:10.1016/j.cels.2018.03.002
 
manubot cite --output manual-references-20200709.json 
@https://gco.iarc.fr/today/data/factsheets/cancers/39-All-cancers-fact-sheet.pdf doi:10.1038/ng.128 doi:10.1056/NEJMra0802714 
```

In the text, 
```
[@doi:10.1016/j.cels.2018.03.002]
```

I really don't know where to start. I suppose that is needed a kind of installation or something in Python but I am not sure.

The information about Manubot is available in:
[Manubot on github](https://github.com/manubot)
[Manubot's web page](https://manubot.org)

My information is in: 
[Bertha's writing](https://github.com/bgrueda/EAPM)

**Comment by abelardoacm** [comment]
You can try Manubot installation within conda, then set an environment with `conda create --name manubot-dev --channel conda-forge \` this way you also limit your tests and the files generated in that environment and avoid problems with other packages.

**Comment by IsauraRReinhold** [comment]
I found this presentation which can be util

Revolutionizing scholarly writing with Manubot - Zenodo

**Comment by IsauraRReinhold** [comment]
manubot cite: automatically generate CSL metadata & formatted references from citation identifiers

https://asciinema.org/a/205085?speed=2

**Comment by IsauraRReinhold** [comment]
I found this video that could help us 

https://manubot.org/docs/getting-started.html

**Comment by bc-anaisabel** [comment]
Have you tried using the rest of the formatting types? 
_Manubot includes an additional layer of citation processing, currently unique to the system. All citations point to a standard identifier, for which Manubot automatically retrieves bibliographic metadata such as the title, authors, and publication date. Table 2 presents the supported identifiers and example citations before and after Manubot processing. Authors can optionally define citation tags to provide short readable alternatives to the citation identifiers. Citation metadata is exported to the Citation Style Language (CSL) JSON Data Items format, an open standard that is widely supported by reference managers [13,14]. However, sometimes external resources provide Manubot with invalid CSL Data, which can cause errors with downstream citation processors, such as pandoc-citeproc (http://hackage.haskell.org/package/pandoc-citeproc). Therefore, Manubot removes invalid fields according to the CSL Data specification (https://github.com/citation-style-language/schema). In cases where automatic retrieval of metadata fails or produces incorrect references—which is most common for URL citations—users can manually provide the correct metadata using common reference formats. Manual metadata also supports references without standard identifiers, such as print-only newspaper articles._
<img width="1063" alt="Screen Shot 2020-12-08 at 8 58 41 AM" src="https://user-images.githubusercontent.com/60661704/101507484-d1bef480-3933-11eb-9a69-4871f9073ef9.png">

**Comment by abelardoacm** [comment]
I think that you can fulfill the task of automatic citation using easy and ready to use tools like, Mendeley, Zotero or even LaTeX. However as a recent enthusiast of collaborative science platforms, I believe Manubot represents a  powerful toolbox for collaborative scientific writing. 

Such emerging platforms are reviewed [here](https://www.nature.com/news/scientific-writing-the-online-cooperative-1.16039), and [a brief history regarding the use of Manubot](http://blogs.nature.com/naturejobs/2018/02/20/techblog-manubot-powers-a-crowdsourced-deep-learning-review/).

**Comment by abelardoacm** [comment]
It will be no surprise to see a more user-friendly compilation of Manubot utilities soon.

**Comment by bgrueda** [comment]
We've concluded that it is a tool that can be useful, however it hasn't yet mature. At the moment it is difficult to follow and use and does not offer advantages over traditional reference managers like Mendeley and a simple document with version control on github
