### ISSUE TITLE
Repository comments

### ISSUE THREAD

**Issue by solouli** [bgrueda/WES_LUAD#8]
Hi, I have some comments that I hope will help you to improve your repo:

- [x] Add open-source license (https://choosealicense.com/)
- [x] Add references in the Introduction
- [x] It would be a good idea to add the directory tree as in Abelardo's repo instead of describing how many subdirectories each one is divided into
- [ ] I don't think it is necessary to describe with text what is inside archive, bin, data, figures and metadata 
- [x] Also, archive is supposed to be a directory that is only on your computer and not in the repository
- [x] If the diagram will be the only thing that explains the steps to follow, it must include the exact name of the scripts used in each step

**Comment by bgrueda** [comment]
I consider that is useful the summary of the content of the directories, the *kind* of information contained in each one.
