### ISSUE TITLE
Preliminary evaluation

### ISSUE THREAD

**Issue by camillethuyentruong** [bgrueda/WES_LUAD#9]
**10% Organización del repositorio**
Make sure all folders described in the README exist and their link are working.

**15% README (debe ser en inglés)**
The description of the repo need to correspond to the repo structure. For example, the archive and metadata folders are missing. Otherwise the description of the project is nice and clear!

**15% Análisis**
Simple and efficient, I like it!

**15% Resumen y discusión en formato Markdown**
Right now the discussion is extremely reduced and need to be illustrated with some figures generated during the analyses. Do you really need to present the results separately in two README? Except if the results are extensive, I suggest joining them into one README

**15% Gráfica(s) en R**
Missing so far

**15% Scripts deben estar comentados en inglés**
I suggest writing a small README describing your pipeline.

Scripts are usually run from bin, calling for the data using a relative path, That way you can create a pipeline to run all your scripts successively in bin.
For example in `1_fastqc.sh`: `mkdir ../data/FastQC_Reports`

**15% Avances, organización y respuesta a comentarios en el proyecto de Github en inglés**
Two of your issues are still open and need to be at least commented. In addition you have no tasks in progress right now on your project!

**Comment by bgrueda** [comment]
Thank you so much, there are so useful comments. I think I have a better version of my repo now. 
Hugs!

**Comment by camillethuyentruong** [comment]
Good job Bertha! Your repo and your scripts are well written and documented!
I only have two small comments:
- The file figures.md is empty - if it is not meant to be you can simply remove it.
- Even though your results are preliminary, they need to be discussed, for example is it what you expected? If not what parameters could changed etc  

I hope you enjoyed the course.
